#version 460
#extension GL_EXT_ray_tracing : enable

layout(binding = 1, rgba8) uniform image2D output_image;

void main() {
    ivec2 coord = ivec2(gl_LaunchIDEXT.xy);
    
    // Visual checkerboard pattern (bypasses AS)
    bool checker = ((coord.x / 20) + (coord.y / 20)) % 2 == 0;
    vec3 color = checker ? vec3(0,1,0) : vec3(1,0,0);
    
    imageStore(output_image, coord, vec4(color, 1.0));
}