[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
glam = "0.30.1"

data = { path = "../data" }
raw-window-handle = "0.6.2"
bytemuck = "1.22.0"
bevy_ecs = "0.15.3"
